/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.Permutacion.generar_vecino;
import java.io.File;
import java.util.Arrays;
import java.util.Scanner;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;

/**
 *
 * @author Magdiel
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jvAbrir = new javax.swing.JButton();
        JvPermutacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jvCosto = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jvAbrir.setText("Abrir");
        jvAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvAbrirActionPerformed(evt);
            }
        });

        JvPermutacion.setText("Generar Permutacion");
        JvPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JvPermutacionActionPerformed(evt);
            }
        });

        jvCosto.setColumns(20);
        jvCosto.setRows(5);
        jvCosto.setText("Costo");
        jScrollPane1.setViewportView(jvCosto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jvAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JvPermutacion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jvAbrir)
                .addGap(18, 18, 18)
                .addComponent(JvPermutacion)
                .addContainerGap(225, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jvAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvAbrirActionPerformed
     final JFileChooser fc = new JFileChooser();// TODO add your handling code here:
     int returnVal = fc.showOpenDialog(this);
       if (returnVal == JFileChooser.APPROVE_OPTION){
          File f  = fc.getSelectedFile();
          TSP tsp;
        tsp = new TSP();
        archivos a = new archivos();
        String s1 = a.leerTxt("f");
            //jvCosto.setText(f.getName());
       }
    }//GEN-LAST:event_jvAbrirActionPerformed

    private void JvPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JvPermutacionActionPerformed
                TSP tsp;
        tsp = new TSP();
        archivos a = new archivos();
        String s1 = a.leerTxt("f");
        
        StringTokenizer string = new StringTokenizer(s1, "#");
        int totalDatos = string.countTokens();
        String[] datos = new String[totalDatos];
        //int i=0;
        while (string.hasMoreTokens()) {
            String str = string.nextToken();
            // encuentra el nombre y lo agrega a una nueva variable    
            if (str.equals("NAME: ")) {
                String str2 = string.nextToken();
                System.out.println("Nombre de archivo: " + str2);
                tsp.setName(str2);
            }
            // guardamos el tipo  
            if (str.equals("TYPE: ")) {
                String str3 = string.nextToken();
                System.out.println("Tipo del archivo: " + str3);
                tsp.setType(str3);
            }

            if (str.equals("COMMENT: ")) {
                String str4 = string.nextToken();
                System.out.println("Comentario: " + str4);
                tsp.setComment(str4);
            }

            if (str.equals("DIMENSION: ")) {
                String str5 = string.nextToken();
                System.out.println("Dimension: " + str5);
                tsp.setDimension(str5);
            }

            if (str.equals("EDGE_WEIGHT_TYPE: ")) {
                String str6 = string.nextToken();
                System.out.println("EDGE_WEIGHT_TYPE: " + str6);
                tsp.setEdgeWeightType(str6);
            }

            if (str.equals("EDGE_WEIGHT_FORMAT: ")) {
                String str7 = string.nextToken();
                System.out.println("EDGE_WEIGHT_FORMAT:" + str7);
                tsp.setEdgeWeightFormat(str7);
            }

            if (str.equals("DISPLAY_DATA_TYPE: ")) {
                String str8 = string.nextToken();
                System.out.println("DISPLAY_DATA_TYPE : " + str8);
                tsp.setDisplayDataType(str8);
            }
            //Para la Matriz
            if (str.equals("EDGE_WEIGHT_SECTION")) {
                String str9 = string.nextToken();
                double[][] distancia = new double[29][29];
                StringTokenizer nuevo = new StringTokenizer(str9);
                for (int x = 0; x < distancia.length; x++) {
                    for (int y = 0; y < distancia[x].length; y++) {
                        //System.out.print(nuevo.nextToken()+ " ");
                        distancia[x][y] = Double.parseDouble(nuevo.nextToken());
                    }
                    //System.out.println(); 
                }

                //System.out.println(distancia[28][28]);
                //Pruebas
                tsp.setDistancia(distancia);
                double m[][] = tsp.getDistancia();
                //System.out.println(m[0][1]); esta fue una prueba
                // Generar caminos aleatorios 
                int valor = 0;
                int[] ciudadesoriginal = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
                // MUESTRA LA MATRIZ CON LAS REINAS ORIGINALES PARA LAS CUALES SE BUSCARAN EL VECINO     
                int[] nuevaruta = ciudadesoriginal;
                System.out.println("ruta original: " + Arrays.toString(nuevaruta));
                //SE PIDE POR PANTALLAS LOS VECINOS QUE QUIERE GENERAR 
                int n;
                System.out.println("Por favor introduzca la cantidad de permutaciones a generar");
                Scanner lector = new Scanner(System.in);
                n = lector.nextInt();
                for (int i = 0; i < n; i++) {
                    generar_vecino(nuevaruta);
                    // FINALMENTE SE MUESTRAN TODOS LOS VECINOS GENERADOS 
                    System.out.println("Permutacion: " + Arrays.toString(nuevaruta));
                    // System.out.println("Permutacion: " + (nuevaruta[1]));
                }
                // Generamos el costo 

                double suma = 0;
                //  System.out.println(""+nuevaruta.length);
                //System.out.println(""+m[0].length);
                int i = 0;
                while (i < nuevaruta.length - 1) {
                    int calculo1 = nuevaruta[i + 1] - 1;
                    int calculo2 = nuevaruta[i] - 1;
                    double calculocosto = m[calculo1][calculo2];
                    suma = suma + calculocosto;
                    i++;
                }
                System.out.println("El costo total es ; " + suma);
                

                String transformar= Double.toString(suma);
               jvCosto.setText(transformar); 

            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_JvPermutacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JvPermutacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jvAbrir;
    private javax.swing.JTextArea jvCosto;
    // End of variables declaration//GEN-END:variables
}
